repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: debug-statements
      -   id: end-of-file-fixer
      -   id: name-tests-test
          args: [--django]
      -   id: requirements-txt-fixer
      -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language: python
        types: [python]
        args: ["--line-length=120"]
